# Generated by Django 5.2.6 on 2025-10-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbluser',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='tbluser',
            table='registration_app_tbluser',
        ),
    ]
