# Generated by Django 5.2.6 on 2025-12-10 08:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard_app', '0008_delete_borrowrequest'),
        ('registration_app', '0002_alter_tbluser_options_alter_tbluser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.tbluser')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.item')),
            ],
            options={
                'db_table': 'dashboard_app_borrowrequest',
            },
        ),
        migrations.CreateModel(
            name='RequestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=32)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('borrow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_app.borrowrequest')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration_app.tbluser')),
            ],
        ),
    ]
