# Generated by Django 5.2.6 on 2025-11-14 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_alter_item_category'),
        ('registration_app', '0002_alter_tbluser_options_alter_tbluser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration_app.tbluser'),
        ),
    ]
