# Generated by Django 5.2.6 on 2025-11-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_item_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
