# Generated by Django 5.2.6 on 2025-12-02 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_auto_20251118_1657'),
        ('registration_app', '0002_alter_tbluser_options_alter_tbluser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_app.tbluser')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.item')),
            ],
        ),
    ]
