# Generated by Django 5.2.6 on 2025-12-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0007_borrowrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowRequest',
        ),
    ]
