# Generated by Django 5.2.6 on 2025-12-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0008_delete_borrowrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
